name: Build Mod DLL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Build Project
      run: |
        msbuild iiMenu.sln /p:Configuration=Release

    - name: Upload DLL Artifact
      uses: actions/upload-artifact@v2.3.0  # Switched to v2.3.0 for stability
      with:
        name: Mod DLL
        path: |
          **/bin/Release/*.dll
